export const CROPS = [
  'apple',
  'banana',
  'blackgram',
  'chickpea',
  'coconut',
  'coffee',
  'cotton',
  'grapes',
  'jute',
  'kidneybeans',
  'lentil',
  'maize',
  'mango',
  'mothbeans',
  'mungbean',
  'muskmelon',
  'orange',
  'papaya',
  'pigeonpeas',
  'pomegranate',
  'rice',
  'watermelon',
] as const;

export type Crop = typeof CROPS[number];

export const CROP_NAMES: Record<Crop, string> = {
  apple: 'Manzana',
  banana: 'Plátano',
  blackgram: 'Frijol Negro',
  chickpea: 'Garbanzo',
  coconut: 'Coco',
  coffee: 'Café',
  cotton: 'Algodón',
  grapes: 'Uvas',
  jute: 'Yute',
  kidneybeans: 'Frijol Rojo',
  lentil: 'Lenteja',
  maize: 'Maíz',
  mango: 'Mango',
  mothbeans: 'Frijol Polilla',
  mungbean: 'Frijol Mungo',
  muskmelon: 'Melón',
  orange: 'Naranja',
  papaya: 'Papaya',
  pigeonpeas: 'Guandú',
  pomegranate: 'Granada',
  rice: 'Arroz',
  watermelon: 'Sandía',
};
